# 
# Synthesis run script generated by Vivado
# 

set_param general.maxThreads 8
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.cache/wt} [current_project]
set_property parent.project_path {C:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo {c:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{c:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/gene.coe}}
add_files {{c:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/codon.coe}}
add_files -quiet {{c:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.srcs/sources_1/ip/codon_memory/codon_memory.dcp}}
set_property used_in_implementation false [get_files {{c:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.srcs/sources_1/ip/codon_memory/codon_memory.dcp}}]
add_files -quiet {{c:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.srcs/sources_1/ip/gene_memory/gene_memory.dcp}}
set_property used_in_implementation false [get_files {{c:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.srcs/sources_1/ip/gene_memory/gene_memory.dcp}}]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.srcs/sources_1/new/codon_reader.sv}
  {C:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.srcs/sources_1/new/codon_counter.sv}
  {C:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.srcs/sources_1/new/hardware_wrapper.sv}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top hardware_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef hardware_wrapper.dcp

catch { report_utilization -file hardware_wrapper_utilization_synth.rpt -pb hardware_wrapper_utilization_synth.pb }
