# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.srcs/sources_1/ip/gene_memory/gene_memory.xci
# IP: The module: 'gene_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.srcs/sources_1/ip/gene_memory/gene_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gene_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.srcs/sources_1/ip/gene_memory/gene_memory.xci
# IP: The module: 'gene_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/heis0741/OneDrive - University of Idaho/U-Drive/ECE 440/Project_8/Project_8.srcs/sources_1/ip/gene_memory/gene_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gene_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
