# 
# Synthesis run script generated by Vivado
# 

set_param general.maxThreads 8
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {U:/ECE 440/Project_5/Project_5.cache/wt} [current_project]
set_property parent.project_path {U:/ECE 440/Project_5/Project_5.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo {u:/ECE 440/Project_5/Project_5.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{U:/ECE 440/Project_5/start_memory.coe}}
add_files -quiet {{U:/ECE 440/Project_5/Project_5.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp}}
set_property used_in_implementation false [get_files {{U:/ECE 440/Project_5/Project_5.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp}}]
read_verilog -library xil_defaultlib -sv {
  {U:/ECE 440/Project_5/Project_5.srcs/sources_1/new/fsm.sv}
  {U:/ECE 440/Project_5/Project_5.srcs/sources_1/new/dp.sv}
  {U:/ECE 440/Project_5/Project_5.srcs/sources_1/new/gcd_core.sv}
  {U:/ECE 440/Project_5/Project_5.srcs/sources_1/new/gcd_calculator.sv}
  {U:/ECE 440/Project_5/Project_5.srcs/sources_1/new/spi.sv}
  {U:/ECE 440/Project_5/Project_5.srcs/sources_1/new/debounce.sv}
  {U:/ECE 440/Project_5/Project_5.srcs/sources_1/new/memory_reader.sv}
  {U:/ECE 440/Project_5/Project_5.srcs/sources_1/new/hardware_wrapper.sv}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{U:/ECE 440/Project_5/Project_5.srcs/constrs_1/new/zybo_master.xdc}}
set_property used_in_implementation false [get_files {{U:/ECE 440/Project_5/Project_5.srcs/constrs_1/new/zybo_master.xdc}}]


synth_design -top hardware_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef hardware_wrapper.dcp

catch { report_utilization -file hardware_wrapper_utilization_synth.rpt -pb hardware_wrapper_utilization_synth.pb }
